export const FSData=[
    {
        href:"https://www.instagram.com/withcameraman/",
        handle:"@withcameraman",
    },
    {
        href:"https://www.instagram.com/arshh_29/",
        handle:"@arsh_29",
    },
    {
        href:"https://www.instagram.com/darshoots/",
        handle:"@darshoots",
    },
    {
        href:"https://www.instagram.com/kartikeyachhikara/",
        handle:"@kartikeyachhikara",
    },
    {
        href:"https://www.instagram.com/count_clicks/",
        handle:"@count_clicks",
    },
    {
        href:"https://www.instagram.com/camerawaleengineer/",
        handle:"@camerawaleengineer",
    },
    {
        href:"https://www.instagram.com/ishkus_land/",
        handle:"@ishkus_land",
    },
    {
        href:"https://www.instagram.com/khatihitesh.jpeg/",
        handle:"@khatihitesh.jpeg",
    },
    {
        href:"https://www.instagram.com/kartikeyachhikara/",
        handle:"@kartikeyachhikara",
    },
];